name: Build File

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check the repository
        uses: actions/checkout@v2

      - name: Deplay the git page
        run: echo "Deplay the git page"

      - name: check Run
        run: |
          echo "Add actions to build, and deploy the git"

